version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_BASE_URL=${GEMINI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_lib:/usr/local/lib/pg_ext:rw
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      retries: 5
